### PR TITLE
Backwards compatible fix for Dart 2.8 changes to HttpHeaders

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes https://github.com/thosakwe/mock_request/issues/2

### CODE REVIEW

**Comment by thosakwe** [comment]
Thanks. This may need to be in a new major version, as the underlying cause is a breaking change. I'll check to see if it works on 2.7.

**Comment by domesticmouse** [comment]
It works for me in Dart 2.7.2. I'll need to check with the Dart language lawyers, but I believe this is a backwards compatiable change.

**Comment by domesticmouse** [comment]
Here’s the breaking change notification: https://github.com/dart-lang/sdk/issues/39657

**Comment by domesticmouse** [comment]
Hi @thosakwe, any guidance on what is required to merge this or a similar change and get it published? Your code base is going to be broken when Dart 2.8 ships, which is [hopefully happening soon](https://groups.google.com/forum/#!topic/flutter-dev/FCPADeOqtyo). I'd like to update my dependencies for Dart 2.8 release if possible =)

**Comment by domesticmouse** [comment]
Ping, Dart 2.8 is almost ready to land and this package will break. What changes are required to land this PR?

**Comment by thosakwe** [comment]
Thanks! Merging. Going to apply `pedantic` fixes, and then publish.

**Comment by domesticmouse** [comment]
Thanks!

**Comment by thosakwe** [comment]
https://pub.dev/packages/mock_request/versions/1.0.7

**Comment by domesticmouse** [comment]
Woot, thank you =)

**Pull request merged**
